import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';

const url = process.env.SUPABASE_URL;
const key = process.env.SUPABASE_ANON_KEY;
const outDir = process.env.CONFIG_OUT_DIR || 'js';
const outPath = join(outDir, 'config.js');

if (!url || !key) {
  console.error('Missing SUPABASE_URL or SUPABASE_ANON_KEY environment variables.');
  process.exit(1);
}

const contents = `// Generated by scripts/generate-config.mjs — do not edit in CI
window.APP_CONFIG = {
  SUPABASE_URL: ${JSON.stringify(url)},
  SUPABASE_ANON_KEY: ${JSON.stringify(key)},
  STORAGE_LIMIT_BYTES: 524288000
};
`;

mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, contents, 'utf8');
console.log('Wrote', outPath);
